### ISSUE TITLE
Non-reproducible error with GoLang 1.5beta3 during compile lots of JS scripts

### ISSUE THREAD

**Issue by guus-vanweelden** [robertkrimen/otto#131]
I compiled my go code with GoLang 1.5beta3 and when my server starts, it has to compile a bunch of JS scripts, since 1.5 I got sometimes a panic.

The JS scripts are very simple, like that:

```javascript
if(typeof Media.Attributes["licenser"] !== "undefined" && Media.Attributes["licenser"] == "1104") {
 Result = false;
}
```

And in 1 of 10 starts I get a panic.

```
runtime stack:
runtime.throw(0xad8a30, 0x15)
  /usr/local/go/src/runtime/panic.go:527 +0x96 fp=0x7fc12984a7b8 sp=0x7fc12984a7a0
runtime.adjustpointers(0xc820af5280, 0x7fc12984a930, 0x7fc12984ab20, 0xd4bc58)
  /usr/local/go/src/runtime/stack1.go:438 +0x2cf fp=0x7fc12984a8b0 sp=0x7fc12984a7b8
runtime.adjustframe(0x7fc12984aa40, 0x7fc12984ab20, 0x7fc100000301)
  /usr/local/go/src/runtime/stack1.go:505 +0x1b5 fp=0x7fc12984a968 sp=0x7fc12984a8b0
runtime.gentraceback(0x40f810, 0xc820af5188, 0x0, 0xc820000180, 0x0, 0x0, 0x7fffffff, 0xbf2e18, 0x7fc12984ab20, 0x0, ...)
  /usr/local/go/src/runtime/traceback.go:336 +0xa7e fp=0x7fc12984aa98 sp=0x7fc12984a968
runtime.copystack(0xc820000180, 0x8000)
  /usr/local/go/src/runtime/stack1.go:616 +0x1a7 fp=0x7fc12984ab88 sp=0x7fc12984aa98
runtime.shrinkstack(0xc820000180)
  /usr/local/go/src/runtime/stack1.go:880 +0x148 fp=0x7fc12984abb8 sp=0x7fc12984ab88
runtime.markroot(0xc820014000, 0x5)
  /usr/local/go/src/runtime/mgcmark.go:130 +0x1ac fp=0x7fc12984ac58 sp=0x7fc12984abb8
runtime.parfordo(0xc820014000)
  /usr/local/go/src/runtime/parfor.go:110 +0x1d4 fp=0x7fc12984ace0 sp=0x7fc12984ac58
runtime.gchelper()
  /usr/local/go/src/runtime/mgc.go:1652 +0x59 fp=0x7fc12984ad28 sp=0x7fc12984ace0
runtime.stopm()
  /usr/local/go/src/runtime/proc1.go:1131 +0x15e fp=0x7fc12984ad50 sp=0x7fc12984ad28
runtime.gcstopm()
  /usr/local/go/src/runtime/proc1.go:1321 +0xfe fp=0x7fc12984ad80 sp=0x7fc12984ad50
runtime.findrunnable(0xc820017500, 0x0)
  /usr/local/go/src/runtime/proc1.go:1366 +0x35 fp=0x7fc12984ae00 sp=0x7fc12984ad80
runtime.schedule()
  /usr/local/go/src/runtime/proc1.go:1623 +0x282 fp=0x7fc12984ae38 sp=0x7fc12984ae00
runtime.park_m(0xc8201ae600)
  /usr/local/go/src/runtime/proc1.go:1682 +0x1ac fp=0x7fc12984ae60 sp=0x7fc12984ae38
runtime.mcall(0x0)
  /usr/local/go/src/runtime/asm_amd64.s:204 +0x5e fp=0x7fc12984ae70 sp=0x7fc12984ae60
  
goroutine 1 [copystack]:
runtime.assertE2I2(0x9d4660, 0x9fe7e0, 0xc8207743c0, 0xc82077d2a0, 0x0)
  /usr/local/go/src/runtime/iface.go:359 fp=0xc820af5190 sp=0xc820af5188
github.com/robertkrimen/otto.toValue(0x9fe7e0, 0xc8207743c0, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/value.go:283 +0x2e7 fp=0xc820af54d8 sp=0xc820af5190
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820217080, 0x7fc126f88120, 0xc8205fe6c0, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:74 +0x3ff fp=0xc820af5648 sp=0xc820af54d8
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeDotExpression(0xc820217080, 0xc8205fcf90, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:253 +0x76 fp=0xc820af5788 sp=0xc820af5648
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820217080, 0x7fc126f88148, 0xc8205fcf90, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:50 +0xc84 fp=0xc820af58f8 sp=0xc820af5788
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc820217080, 0xc8205fcfc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:182 +0x8a fp=0xc820af5bb8 sp=0xc820af58f8
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820217080, 0x7fc126f88328, 0xc8205fcfc0, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f fp=0xc820af5d28 sp=0xc820af5bb8
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc820217080, 0x7fc126f88288, 0xc820213ad0, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:59 +0x1283 fp=0xc820af6070 sp=0xc820af5d28
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc820217080, 0xc820397000, 0x71, 0x71, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:118 +0xe5 fp=0xc820af6128 sp=0xc820af6070
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc820217080, 0x7fc126f882b0, 0xc820688ec0, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:30 +0x517 fp=0xc820af6470 sp=0xc820af6128
github.com/robertkrimen/otto.(*_runtime).cmpl_call_nodeFunction(0xc820217080, 0xc8205004e0, 0xc8209c7530, 0xc82068e180, 0x5, 0xa53380, 0xc820156f60, 0xc82068c8e0, 0x0, 0x0, ...)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate.go:61 +0x5e5 fp=0xc820af65e0 sp=0xc820af6470
github.com/robertkrimen/otto.(*_object).call(0xc8205004e0, 0x5, 0xa53380, 0xc820156f60, 0xc82068c8e0, 0x0, 0x0, 0xc81ffb1c00, 0x0, 0x0, ...)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/type_function.go:154 +0x27e fp=0xc820af6880 sp=0xc820af65e0
github.com/robertkrimen/otto.builtinFunction_call(0xc820217080, 0xc8205004e0, 0x0, 0x5, 0xa53380, 0xc8205004e0, 0xc82068c8e0, 0x1, 0x1, 0xc82057cba0, ...)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/builtin_function.go:109 +0x37d fp=0xc820af6a98 sp=0xc820af6880
github.com/robertkrimen/otto.(*_object).call(0xc820157380, 0x5, 0xa53380, 0xc8205004e0, 0xc82068c8e0, 0x1, 0x1, 0x0, 0xc820334540, 0x0, ...)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/type_function.go:140 +0x531 fp=0xc820af6d38 sp=0xc820af6a98
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc820217080, 0xc8209c7470, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:240 +0x9a1 fp=0xc820af6ff8 sp=0xc820af6d38
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820217080, 0x7fc126f88328, 0xc8209c7470, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f fp=0xc820af7168 sp=0xc820af6ff8
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc820217080, 0x7fc126f88288, 0xc82023eb40, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:59 +0x1283 fp=0xc820af74b0 sp=0xc820af7168
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc820217080, 0xc8201ff7e0, 0x1, 0x1, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:118 +0xe5 fp=0xc820af7568 sp=0xc820af74b0
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc820217080, 0xc820405810, 0xc820af7600, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/cmpl_evaluate.go:17 +0x2d8 fp=0xc820af7628 sp=0xc820af7568
github.com/robertkrimen/otto.(*_runtime).cmpl_run.func1()
  /home/vanweelden/go/src/github.com/robertkrimen/otto/runtime.go:363 +0x37 fp=0xc820af7680 sp=0xc820af7628
github.com/robertkrimen/otto.catchPanic(0xc820af7700, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/error.go:243 +0x5c fp=0xc820af76a0 sp=0xc820af7680
github.com/robertkrimen/otto.(*_runtime).cmpl_run(0xc820217080, 0x8e4760, 0xc82057cf00, 0x0, 0x0, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/runtime.go:364 +0x12b fp=0xc820af7728 sp=0xc820af76a0
github.com/robertkrimen/otto.Otto.Run(0x0, 0xc820217080, 0x8e4760, 0xc82057cf00, 0x0, 0x0, 0x0, 0x0, 0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/otto.go:292 +0x5c fp=0xc820af7770 sp=0xc820af7728
github.com/robertkrimen/otto.New.func1(0x1, 0xbf2928)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/otto.go:250 +0xa0 fp=0xc820af77d8 sp=0xc820af7770
github.com/robertkrimen/otto/registry.Apply(0xc820af7888)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/registry/registry.go:39 +0x91 fp=0xc820af7820 sp=0xc820af77d8
github.com/robertkrimen/otto.New(0x0)
  /home/vanweelden/go/src/github.com/robertkrimen/otto/otto.go:251 +0x102 fp=0xc820af78a0 sp=0xc820af7820
```

**Comment by dop251** [comment]
If it worked with 1.4 you should report this as a bug in go: https://github.com/golang/go/issues

**Comment by robertkrimen** [comment]
Are you cloning/copying VMs at all, or instantiating new ones?

**Comment by deoxxa** [comment]
@guus-vanweelden does this still happen? If so, can you supply some code to reproduce the bug?

**Comment by deoxxa** [comment]
I'm closing this for now. Feel free to open a new issue if you can reliably reproduce this bug.
