### ISSUE TITLE
FIXME TypeError

### ISSUE THREAD

**Issue by lycis** [robertkrimen/otto#236]
I am hitting a panic upon calling a function that resides in a script with the following stack trace:

```
panic: FIXME TypeError [recovered]
	panic: FIXME TypeError

goroutine 6 [running]:
panic(0x6760a0, 0xc04214e1a0)
	C:/Go/src/runtime/panic.go:500 +0x1af
github.com/lycis/kami/vendor/github.com/robertkrimen/otto.catchPanic.func1(0xc04202bca8)
	C:/Users/edd/go/src/github.com/lycis/kami/vendor/github.com/robertkrimen/otto/error.go:247 +0x3f3
panic(0x6760a0, 0xc04214e1a0)
	C:/Go/src/runtime/panic.go:458 +0x251
github.com/lycis/kami/vendor/github.com/robertkrimen/otto.Value.call(0x0, 0x0, 0x0, 0x0, 0x5, 0x6bf6a0, 0xc042156000, 0x0, 0x0, 0x0, ...)
	C:/Users/edd/go/src/github.com/lycis/kami/vendor/github.com/robertkrimen/otto/value.go:126 +0x20f
github.com/lycis/kami/vendor/github.com/robertkrimen/otto.Value.Call.func1()
	C:/Users/edd/go/src/github.com/lycis/kami/vendor/github.com/robertkrimen/otto/value.go:112 +0x9e
github.com/lycis/kami/vendor/github.com/robertkrimen/otto.catchPanic(0xc04202bcd0, 0x0, 0x0)
	C:/Users/edd/go/src/github.com/lycis/kami/vendor/github.com/robertkrimen/otto/error.go:250 +0x73
github.com/lycis/kami/vendor/github.com/robertkrimen/otto.Value.Call(0x0, 0x0, 0x0, 0x5, 0x6bf6a0, 0xc042156000, 0x0, 0x0, 0x0, 0x40f1f8, ...)
	C:/Users/edd/go/src/github.com/lycis/kami/vendor/github.com/robertkrimen/otto/value.go:113 +0xe9
github.com/lycis/kami/vendor/github.com/robertkrimen/otto.Otto.Call(0x0, 0xc042010600, 0x6cbd65, 0xc, 0x690a80, 0xc04213e380, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Users/edd/go/src/github.com/lycis/kami/vendor/github.com/robertkrimen/otto/otto.go:593 +0x3cb
github.com/lycis/kami/script.Instance.Call(0xc0420f9f10, 0x0, 0x6cbd65, 0xc, 0x690a80, 0xc04213e380, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Users/edd/go/src/github.com/lycis/kami/script/instance.go:16 +0x16d
github.com/lycis/kami/entity.(*Entity).Heartbeat(0xc04213e380)
	C:/Users/edd/go/src/github.com/lycis/kami/entity/entity.go:41 +0x8b
```

Is this my fault or maybe something I can workaround until it is fixed?

**Comment by lycis** [comment]
Actually I found my error. I was calling for a syntactically wring defined function. Still it would be great to improve the error message here.

**Comment by stevenh** [comment]
If you have an example we can look at it but for now closing as it wasn't a bug.
