### ISSUE TITLE
panic: Assigning value to output array from array outside it's length gives panic on export

### ISSUE THREAD

**Issue by MichaelS11** [robertkrimen/otto#242]
When assigning values from two arrays and assigning the data to a new array, can access elements outside the second array length. Then when exporting the new array, Go gives a panic. While it is bad JavaScript code, seems like it should give a JavaScript run time error instead of a panic on export.

```go
package main

import (
	"fmt"

	"github.com/robertkrimen/otto"
)

func main() {

	vm := otto.New()

	_, err := vm.Run(`
var output = [[]];

array1 = ["11", "12", "13"];
array2 = ["21", "22"];

for (i = 0; i < array1.length; i++) {
  output[i] = [array1[i], array2[i]];
}
`)

	if err != nil {
		fmt.Println(err)
		return
	}

	outputValue, err := vm.Get("output")
	if err != nil {
		fmt.Println(err)
		return
	}

	outputInterface, _ := outputValue.Export()

	fmt.Println(outputInterface)
}
```

panic: reflect.Set: value of type []string is not assignable to type []interface {}

goroutine 1 [running]:
panic(0x65f2e0, 0xc04211f330)
	C:/app/Go/src/runtime/panic.go:500 +0x1af
reflect.Value.assignTo(0x65c560, 0xc042124f00, 0x97, 0x6a79eb, 0xb, 0x65bba0, 0x0, 0x0, 0x65c560, 0xc042124f00)
	C:/app/Go/src/reflect/value.go:2163 +0x363
reflect.Value.Set(0x65bba0, 0xc04207a780, 0x197, 0x65c560, 0xc042124f00, 0x97)
	C:/app/Go/src/reflect/value.go:1333 +0xab
vendor/github.com/robertkrimen/otto.Value.export(0x5, 0x69cf60, 0xc04210fb60, 0x0, 0x0)
	C:/Users/username/Documents/Eclipse/src/vendor/github.com/robertkrimen/otto/value.go:718 +0xe8a
vendor/github.com/robertkrimen/otto.Value.Export(0x5, 0x69cf60, 0xc04210fb60, 0x0, 0x0, 0x0, 0x0)
	C:/Users/username/Documents/Eclipse/src/vendor/github.com/robertkrimen/otto/value.go:648 +0x6e
main.main()
	C:/Users/username/Documents/Eclipse/src/test/main.go:35 +0x2fe

**Comment by MichaelS11** [comment]
Here is an even more simple JavaScript example that panics in the same otto value Export location and error message.

```JavaScript
var output = [[]];
output[1] = ["21"];
```
