### ISSUE TITLE
I want to call js function array in golang

### ISSUE THREAD

**Issue by guonaihong** [robertkrimen/otto#306]
I want to call js function array in golang  
```golang
package main

import (
	"fmt"
	"github.com/robertkrimen/otto"
	_ "net/http"
)

var jscode = `
function Location(location) {

    return function() {
        console.log("hello")
    }
}

var locations = [
    new Location({reg:"^~ /helloworld", code:601}),
    new Location({reg:"/helloworld", code:602}),
    new Location({reg:"/helloworld", code:603}),
]

var obj = {
	"location": locations,
};
`

func main() {

	vm := otto.New()
	vm.Run(jscode)

	obj, err := vm.Get("obj")
	if err != nil {
		panic(err.Error())
	}

	location, err := obj.Object().Get("location")
	if err != nil {
		panic(err.Error())
	}

	/* js code
	for (var i in obj.location) {
		obj.location[i]();
	}
	*/
	fmt.Printf("%T\n", location)
        //I need to write this way do not output undefined
	location.Object().Call("location[0]")
}
```

**Comment by gen0cide** [comment]
Just looking at this, I think you can. You just need to change `location.Object().Call("location[0]")` to `location.Object().Call("location[0]()")`. I don't think you were ever actually calling the `new Location` function in the first place.

**Comment by guonaihong** [comment]
Thanks for gen0cide's music.
The output of running location.Object().Call("location[0]") is
```bash
otto.Value
panic: FIXME TypeError [recovered]
	panic: FIXME TypeError

goroutine 1 [running]:
github.com/robertkrimen/otto.catchPanic.func1(0xc42014fd88)
	/home/guo/src/github.com/robertkrimen/otto/error.go:248 +0x561
panic(0x7a8c60, 0x8ebf40)
	/home/guo/go-version/go1.9.2/src/runtime/panic.go:491 +0x283
github.com/robertkrimen/otto.Value.call(0x0, 0x0, 0x0, 0x0, 0x5, 0x81cea0, 0xc42017c540, 0x0, 0x0, 0x0, ...)
	/home/guo/src/github.com/robertkrimen/otto/value.go:126 +0x1b9
github.com/robertkrimen/otto.Value.Call.func1()
	/home/guo/src/github.com/robertkrimen/otto/value.go:112 +0x8b
github.com/robertkrimen/otto.catchPanic(0xc42014fdb0, 0x0, 0x0)
	/home/guo/src/github.com/robertkrimen/otto/error.go:251 +0x63
github.com/robertkrimen/otto.Value.Call(0x0, 0x0, 0x0, 0x5, 0x81cea0, 0xc42017c540, 0x0, 0x0, 0x0, 0x0, ...)
	/home/guo/src/github.com/robertkrimen/otto/value.go:110 +0xe2
github.com/robertkrimen/otto.Object.Call(0xc42017c540, 0x5, 0x81cea0, 0xc42017c540, 0x82ba83, 0xb, 0x0, 0x0, 0x0, 0x0, ...)
	/home/guo/src/github.com/robertkrimen/otto/otto.go:687 +0x130
main.main()
	/home/guo/306.go:50 +0x28d
exit status 2

```

**Comment by stevenh** [comment]
What you need here is to just call `0` not `locations[0]` e.g.
```go
func Test_test306(t *testing.T) {
	vm := New()

	jscode := `
function Location(location) {
    return function() {
        console.log("hello")
    }
}

var locations = [
    new Location({reg:"^~ /helloworld", code:601}),
    new Location({reg:"/helloworld", code:602}),
    new Location({reg:"/helloworld", code:603}),
]

var obj = {
	"location": locations,
};
`
	_, err := vm.Run(jscode)
	require.NoError(t, err)

	obj, err := vm.Get("obj")
	require.NoError(t, err)

	location, err := obj.Object().Get("location")
	require.NoError(t, err)

	_, err = location.Object().Call("0")
	require.NoError(t, err)
}
```
