### ISSUE TITLE
I get this error recently!!

### ISSUE THREAD

**Issue by 756445638** [robertkrimen/otto#343]
fatal error: concurrent map read and map write

goroutine 2557 [running]:
runtime.throw(0xc168a8, 0x21)
	C:/Go/src/runtime/panic.go:608 +0x79 fp=0xc000830cc8 sp=0xc000830c98 pc=0x4308e9
runtime.mapaccess2_faststr(0xb3cb60, 0xc000570540, 0xc0005908a6, 0x6, 0xc0005430d8, 0x30001)
	C:/Go/src/runtime/map_faststr.go:110 +0x45f fp=0xc000830d38 sp=0xc000830cc8 pc=0x4144ef
github.com/robertkrimen/otto.(*_object)._write(...)
	D:/golib/src/github.com/robertkrimen/otto/object.go:135
github.com/robertkrimen/otto.objectDefineOwnProperty(0xc00024c180, 0xc0005908a6, 0x6, 0xbf1d00, 0xc000bfd820, 0x49, 0xc000bfd800, 0xc000bfd820)
	D:/golib/src/github.com/robertkrimen/otto/object_class.go:437 +0x33c fp=0xc000830f60 sp=0xc000830d38 pc=0x944cdc
github.com/robertkrimen/otto.(*_object).defineOwnProperty(0xc00024c180, 0xc0005908a6, 0x6, 0xbf1d00, 0xc000bfd820, 0x49, 0x95c400, 0xc000003680)
	D:/golib/src/github.com/robertkrimen/otto/object.go:110 +0x78 fp=0xc000830fb0 sp=0xc000830f60 pc=0x942d98
github.com/robertkrimen/otto.objectPut(0xc00024c180, 0xc0005908a6, 0x6, 0x4, 0xb10300, 0xa72e60, 0xb68f00)
	D:/golib/src/github.com/robertkrimen/otto/object_class.go:264 +0x153 fp=0xc000831098 sp=0xc000830fb0 pc=0x9446d3
github.com/robertkrimen/otto.(*_object).put(0xc00024c180, 0xc0005908a6, 0x6, 0x4, 0xb10300, 0xa72e60, 0xb68f00)
	D:/golib/src/github.com/robertkrimen/otto/object.go:52 +0x75 fp=0xc0008310e0 sp=0xc000831098 pc=0x9427c5
github.com/robertkrimen/otto.(*_propertyReference).putValue(0xc000bd1cb0, 0x4, 0xb10300, 0xa72e60, 0xb702c0, 0xc000bd1cb0)
	D:/golib/src/github.com/robertkrimen/otto/type_reference.go:45 +0x76 fp=0xc000831128 sp=0xc0008310e0 pc=0x95c0c6
github.com/robertkrimen/otto.(*_runtime).putValue(0xc000003680, 0xd61920, 0xc000bd1cb0, 0x4, 0xb10300, 0xa72e60)
	D:/golib/src/github.com/robertkrimen/otto/runtime.go:108 +0x5d fp=0xc000831180 sp=0xc000831128 pc=0x94a75d
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeAssignExpression(0xc000003680, 0xc00090d890, 0xc00090db60, 0xc000590872, 0xc000003680)
	D:/golib/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:132 +0x16a fp=0xc000831218 sp=0xc000831180 pc=0x8fa78a
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc000003680, 0xd5a660, 0xc00090d890, 0x8000000000000000, 0x0, 0x808ad2d227bd34ac)
	D:/golib/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:31 +0x628 fp=0xc000831300 sp=0xc000831218 pc=0x8f9c38
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc000003680, 0xd5a7c0, 0xc0009bc490, 0x0, 0x0, 0x0)
	D:/golib/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:62 +0xeea fp=0xc0008315c0 sp=0xc000831300 pc=0x8febfa
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc000003680, 0xc0009bc480, 0x1, 0x1, 0xc000bfd7c0, 0x0, 0xc000055880)
	D:/golib/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:121 +0x95 fp=0xc000831628 sp=0xc0008315c0 pc=0x8ff025
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc000003680, 0xd5a6a0, 0xc000e65700, 0x0, 0x0, 0x0)
	D:/golib/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:30 +0x573 fp=0xc0008318e8 sp=0xc000831628 pc=0x8fe283
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeIfStatement(0xc000003680, 0xc00090d8c0, 0xc00090d830, 0x4, 0xb10300)
	D:/golib/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:294 +0xc8 fp=0xc000831928 sp=0xc0008318e8 pc=0x9001b8
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc000003680, 0xd5a860, 0xc00090d8c0, 0x0, 0x0, 0x0)
	D:/golib/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:71 +0xdc7 fp=0xc000831be8 sp=0xc000831928 pc=0x8fead7
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc000003680, 0xc00090d7a0, 0x3, 0x3, 0xc0001a40e0, 0xc000a22aa0, 0xc000c80700)
	D:/golib/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:121 +0x95 fp=0xc000831c50 sp=0xc000831be8 pc=0x8ff025
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc000003680, 0xc0001a40e0, 0x42f500, 0x0, 0x0, 0x0)
	D:/golib/src/github.com/robertkrimen/otto/cmpl_evaluate.go:17 +0xe9 fp=0xc000831c98 sp=0xc000831c50 pc=0x8f8d29
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
	D:/golib/src/github.com/robertkrimen/otto/runtime.go:671 +0x4b fp=0xc000831ce0 sp=0xc000831c98 pc=0x96d89b
github.com/robertkrimen/otto.catchPanic(0xc000831d78, 0x0, 0x0)
	D:/golib/src/github.com/robertkrimen/otto/error.go:250 +0x5c fp=0xc000831d08 sp=0xc000831ce0 pc=0x907dcc
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc000003680, 0xb16140, 0xc000e23b30, 0x0, 0x0, 0x0, 0x10, 0xc000e23b30, 0x0, 0xc000055180, ...)
	D:/golib/src/github.com/robertkrimen/otto/runtime.go:670 +0x116 fp=0xc000831db0 sp=0xc000831d08 pc=0x94f846
github.com/robertkrimen/otto.(*_runtime).cmpl_run(0xc000003680, 0xb16140, 0xc000e23b30, 0x0, 0x0, 0x40b64f, 0x10, 0xb16140, 0x1, 0xc000e23b30)
	D:/golib/src/github.com/robertkrimen/otto/runtime.go:683 +0x69 fp=0xc000831e18 sp=0xc000831db0 pc=0x94f9e9
github.com/robertkrimen/otto.Otto.Run(0x0, 0xc000003680, 0xb16140, 0xc000e23b30, 0x6c7b3d, 0xc0006e4360, 0xc0006f5f00, 0x2, 0x1)
	D:/golib/src/github.com/robertkrimen/otto/otto.go:295 +0x52 fp=0xc000831e78 sp=0xc000831e18 pc=0x9464e2
hmi-server/reportServer/report.(*Report).ifCronNeed(0x117f060, 0xc0002ee480, 0xc00077ac00)
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/reportServer/report/cron.go:107 +0xa3 fp=0xc000831f18 sp=0xc000831e78 pc=0x9b4913
hmi-server/reportServer/report.(*Report).start.func1()
	D:/backstage/newest/hmi-server/code/gopath/src/hmi-server/reportServer/report/cron.go:138 +0x61 fp=0xc000831f90 sp=0xc000831f18 pc=0x9b5ee1
github.com/robfig/cron.FuncJob.Run(0xc00027eaa0)
	D:/golib/src/github.com/robfig/cron/cron.go:92 +0x2c fp=0xc000831fa0 sp=0xc000831f90 pc=0x9ac28c
github.com/robfig/cron.(*Cron).runWithRecovery(0xc0000ac370, 0xd5b940, 0xc00027eaa0)
	D:/golib/src/github.com/robfig/cron/cron.go:165 +0x5e fp=0xc000831fc8 sp=0xc000831fa0 pc=0x9ac8fe
runtime.goexit()
	C:/Go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000831fd0 sp=0xc000831fc8 pc=0x45ec01
created by github.com/robfig/cron.(*Cron).run
	D:/golib/src/github.com/robfig/cron/cron.go:199 +0x6fb

**Comment by azukaar** [comment]
Similar error : 

```
fatal error: concurrent map writes

goroutine 658 [running]:
runtime.throw(0x156451e, 0x15)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:617 +0x72 fp=0xc0065ad050 sp=0xc0065ad020 pc=0x102da52
runtime.mapassign(0x14d3640, 0xc007dd11a0, 0xc00806ff50, 0x100dff8)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/map.go:590 +0x5e3 fp=0xc0065ad0d8 sp=0xc0065ad050 pc=0x100fde3
reflect.mapassign(0x14d3640, 0xc007dd11a0, 0xc00806ff50, 0xc00806ff60)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/map.go:1331 +0x3f fp=0xc0065ad108 sp=0xc0065ad0d8 pc=0x101186f
reflect.Value.SetMapIndex(0x14d3640, 0xc007dd11a0, 0x15, 0x14b69c0, 0xc00806ff50, 0x98, 0x14d13c0, 0xc00806ff60, 0x94)
	/usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:1615 +0x234 fp=0xc0065ad170 sp=0xc0065ad108 pc=0x10bb364
github.com/robertkrimen/otto.goMapDefineOwnProperty(0xc0080667e0, 0xc00807e708, 0x3, 0x15559a0, 0xc0080d0ee0, 0x49, 0x14b6900, 0x1)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/type_go_map.go:86 +0x423 fp=0xc0065ad2b8 sp=0xc0065ad170 pc=0x13dec83
github.com/robertkrimen/otto.(*_object).defineOwnProperty(...)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/object.go:110
github.com/robertkrimen/otto.(*_object).defineProperty(...)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/object.go:105
github.com/robertkrimen/otto.objectPut(0xc0080667e0, 0xc00807e708, 0x3, 0x3, 0x14b69c0, 0xc00806ff30, 0xc0080e2800)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/object_class.go:266 +0x21e fp=0xc0065ad3e0 sp=0xc0065ad2b8 pc=0x13c51fe
github.com/robertkrimen/otto.(*_object).put(...)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/object.go:52
github.com/robertkrimen/otto.(*_propertyReference).putValue(0xc0080e28d0, 0x3, 0x14b69c0, 0xc00806ff30, 0x1, 0x1639f60)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/type_reference.go:45 +0x78 fp=0xc0065ad428 sp=0xc0065ad3e0 pc=0x13e1668
github.com/robertkrimen/otto.(*_runtime).putValue(0xc0078e2f00, 0x1639f60, 0xc0080e28d0, 0x3, 0x14b69c0, 0xc00806ff30)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/runtime.go:110 +0x62 fp=0xc0065ad4a8 sp=0xc0065ad428 pc=0x13cbbc2
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeAssignExpression(0xc0078e2f00, 0xc008045d70, 0x3, 0x14b69c0, 0xc00806fca0)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:132 +0x163 fp=0xc0065ad540 sp=0xc0065ad4a8 pc=0x137bc83
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc0078e2f00, 0x162e060, 0xc008045d70, 0x3, 0x14b69c0, 0xc00806fca0)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:31 +0x673 fp=0xc0065ad618 sp=0xc0065ad540 pc=0x137b123
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc0078e2f00, 0x162e1c0, 0xc00806fbf0, 0x0, 0x0, 0x0)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:62 +0xf4d fp=0xc0065ad7f8 sp=0xc0065ad618 pc=0x138065d
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc0078e2f00, 0xc0080c6000, 0x8, 0x8, 0x0, 0x7, 0x1)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:121 +0x8e fp=0xc0065ad860 sp=0xc0065ad7f8 pc=0x1380b1e
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc0078e2f00, 0xc007f335e0, 0x102c700, 0x0, 0x0, 0x0)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/cmpl_evaluate.go:17 +0xe5 fp=0xc0065ad8b8 sp=0xc0065ad860 pc=0x137a0e5
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/runtime.go:767 +0x44 fp=0xc0065ad900 sp=0xc0065ad8b8 pc=0x13f3914
github.com/robertkrimen/otto.catchPanic(0xc0065ad998, 0x0, 0x0)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/error.go:251 +0x55 fp=0xc0065ad928 sp=0xc0065ad900 pc=0x1388f05
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc0078e2f00, 0x14b69c0, 0xc00806e270, 0x0, 0x0, 0xc0008e5a00, 0x100b589, 0x10, 0x14b67c0, 0x1997d01, ...)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/runtime.go:766 +0x10f fp=0xc0065ad9d0 sp=0xc0065ad928 pc=0x13d2bff
github.com/robertkrimen/otto.(*_runtime).cmpl_run(...)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/runtime.go:779
github.com/robertkrimen/otto.Otto.Run(0x0, 0xc0078e2f00, 0x14b69c0, 0xc00806e270, 0x14d3640, 0xc007dd11a0, 0x0, 0x0, 0x33)
	/Users/yanstepi/go/src/github.com/robertkrimen/otto/otto.go:295 +0x54 fp=0xc0065ada38 sp=0xc0065ad9d0 pc=0x13c7394
_/Users/yanstepi/dev/GuPM/src/jsVm.Run(0xc007b6c500, 0x33, 0xc0008e5c20, 0x15681be, 0x1d, 0xc007b6c500, 0x33, 0xc000062be8)
	/Users/yanstepi/dev/GuPM/src/jsVm/jsVm.go:39 +0x1ef fp=0xc0065adb80 sp=0xc0065ada38 pc=0x14045ff
_/Users/yanstepi/dev/GuPM/src/provider.ResolveDependencyLocation(0xc007dd11a0, 0xc007dd11a0, 0x155f46b, 0x8)
	/Users/yanstepi/dev/GuPM/src/provider/provider.go:139 +0x2ff fp=0xc0065add70 sp=0xc0065adb80 pc=0x140960f
main.expandDepList.func1(0xc0000bd488, 0x1, 0x1, 0xc00025dd40, 0x0, 0xc007dd11a0)
	/Users/yanstepi/dev/GuPM/src/installProject.go:22 +0xc3 fp=0xc0065adfb0 sp=0xc0065add70 pc=0x146b3c3
runtime.goexit()
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0065adfb8 sp=0xc0065adfb0 pc=0x1059931
created by main.expandDepList
	/Users/yanstepi/dev/GuPM/src/installProject.go:20 +0x94

```

**Comment by PeerXu** [comment]
Similar error too:
```
fatal error: concurrent map writes

goroutine 163938 [running]:
runtime.throw(0x16b5ec3, 0x15)
	runtime/panic.go:1117 +0x72 fp=0xc0009ca638 sp=0xc0009ca608 pc=0x436672
runtime.mapassign_faststr(0x14904c0, 0xc000cd0720, 0x16a85fa, 0x9, 0x230b300)
	runtime/map_faststr.go:211 +0x3f1 fp=0xc0009ca6a0 sp=0xc0009ca638 pc=0x414711
github.com/robertkrimen/otto.(*_dclStash).createBinding(0xc000cd06f0, 0x16a85fa, 0x9, 0x0, 0x5, 0x165f620, 0xc0007fd380)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/stash.go:172 +0x90 fp=0xc0009ca6f8 sp=0xc0009ca6a0 pc=0x767fd0
github.com/robertkrimen/otto.(*_dclStash).setValue(0xc000cd06f0, 0x16a85fa, 0x9, 0x5, 0x165f620, 0xc0007fd380, 0x0)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/stash.go:195 +0xf4 fp=0xc0009ca740 sp=0xc0009ca6f8 pc=0x7684d4
github.com/robertkrimen/otto.(*_runtime).cmpl_call_nodeFunction(0xc0008bfc80, 0xc0007fd1a0, 0xc000cd06f0, 0xc000a67c00, 0x0, 0x0, 0x0, 0x23086e0, 0x0, 0x0, ...)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/cmpl_evaluate.go:48 +0x2fc fp=0xc0009ca7f0 sp=0xc0009ca740 pc=0x70ce5c
github.com/robertkrimen/otto.(*_object).call(0xc0007fd1a0, 0x0, 0x0, 0x0, 0x23086e0, 0x0, 0x0, 0xc0001b5000, 0x0, 0x0, ...)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/type_function.go:226 +0x238 fp=0xc0009cab48 sp=0xc0009ca7f0 pc=0x76e9f8
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc0008bfc80, 0xc000cd05d0, 0x0, 0x0, 0x0, 0x23086e0, 0xc000a67c00, 0x203000)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/cmpl_evaluate_expression.go:244 +0x3fd fp=0xc0009cade8 sp=0xc0009cab48 pc=0x70f8dd
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc0008bfc80, 0x19af380, 0xc000cd05d0, 0x7f99f8330a68, 0x40, 0xc000a15b00)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/cmpl_evaluate_expression.go:44 +0x473 fp=0xc0009cae98 sp=0xc0009cade8 pc=0x70d833
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc0008bfc80, 0x19af440, 0xc000a0af10, 0x0, 0x0, 0x0)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/cmpl_evaluate_statement.go:62 +0xd6b fp=0xc0009cb0b0 sp=0xc0009cae98 pc=0x713ceb
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc0008bfc80, 0xc000a0abb0, 0x1, 0x1, 0x0, 0x0, 0x0)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/cmpl_evaluate_statement.go:121 +0x97 fp=0xc0009cb130 sp=0xc0009cb0b0 pc=0x714557
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc0008bfc80, 0xc0001e00e0, 0x0, 0x0, 0x0, 0x0)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/cmpl_evaluate.go:17 +0xfa fp=0xc0009cb1a0 sp=0xc0009cb130 pc=0x70c9fa
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/runtime.go:819 +0x45 fp=0xc0009cb1e8 sp=0xc0009cb1a0 pc=0x786565
github.com/robertkrimen/otto.catchPanic(0xc0009cb2a0, 0x0, 0x0)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/error.go:251 +0x5b fp=0xc0009cb218 sp=0xc0009cb1e8 pc=0x71cc9b
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc0008bfc80, 0x140f680, 0xc000a0a940, 0x0, 0x0, 0xc0009cb300, 0x40b49b, 0x10, 0x140f480, 0x165f601, ...)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/runtime.go:818 +0x125 fp=0xc0009cb2d8 sp=0xc0009cb218 pc=0x7665e5
github.com/robertkrimen/otto.(*_runtime).cmpl_run(...)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/runtime.go:831
github.com/robertkrimen/otto.Otto.Run(0x0, 0xc0008bfc80, 0x140f680, 0xc000a0a940, 0x0, 0xc000cc3830, 0x0, 0x0, 0x7f99d169fb30)
	github.com/robertkrimen/otto@v0.0.0-20210614181706-373ff5438452/otto.go:295 +0x53 fp=0xc0009cb340 sp=0xc0009cb2d8 pc=0x759933
github.com/nayotta/floor15/pkg/machiner/otto.(*OttoMachiner).Execute(0xc0002060e8, 0x19cccc8, 0xc00004c030, 0xc000cc38f0, 0xc000096b60, 0x1, 0x1, 0x16a3e4a, 0x16a3e4a, 0x0, ...)
	github.com/nayotta/floor15/pkg/machiner/otto/otto.go:27 +0x1a5 fp=0xc0009cb408 sp=0xc0009cb340 pc=0x79c7c5
github.com/nayotta/floor15/pkg/specification.genShapeFunc.func1(0x0, 0x0, 0x19d4238, 0xc000c88f48, 0x19cccc8, 0xc00004c030, 0xc000cc38f0, 0x3, 0xc0001ff5bc, 0x152baa0, ...)
	github.com/nayotta/floor15/pkg/specification/shaper.go:82 +0x271 fp=0xc0009cb4d0 sp=0xc0009cb408 pc=0x7a9ff1
github.com/nayotta/floor15/pkg/specification.sf_map(0x0, 0x0, 0x19d4238, 0xc000c88f48, 0x19cccc8, 0xc00004c030, 0xc000cc38f0, 0x41437b, 0xc0009cb610, 0x9215e044, ...)
	github.com/nayotta/floor15/pkg/specification/shaper.go:120 +0xcc fp=0xc0009cb558 sp=0xc0009cb4d0 pc=0x7a690c
github.com/nayotta/floor15/pkg/specification.ShapeImplementation(0x0, 0x0, 0x19d4238, 0xc000c88f48, 0x19cccc8, 0xc00004c030, 0xc000cc38f0, 0x1490fa0, 0xc000cc3830, 0x0, ...)
	github.com/nayotta/floor15/pkg/specification/shaper.go:63 +0x115 fp=0xc0009cb600 sp=0xc0009cb558 pc=0x7a6595
github.com/nayotta/floor15/pkg/specification.(*fieldImplementation).Shape(0xc000c88f48, 0x19cccc8, 0xc00004c030, 0x1490fa0, 0xc000757020, 0xc000096b40, 0x1, 0x1, 0x8, 0x1417bc0, ...)
	github.com/nayotta/floor15/pkg/specification/implementation.go:55 +0x212 fp=0xc0009cb690 sp=0xc0009cb600 pc=0x7a2cb2
github.com/nayotta/floor15/pkg/specification.(*datapathSlot).Shape(0xc000207538, 0x19cccc8, 0xc00004c030, 0x1490fa0, 0xc000757020, 0xc000096b40, 0x1, 0x1, 0x0, 0x0, ...)
	github.com/nayotta/floor15/pkg/specification/device.go:433 +0x9b fp=0xc0009cb700 sp=0xc0009cb690 pc=0x7a259b
github.com/nayotta/floor15/pkg/service/winery.(*MakerServiceImpl).Brew(0xc000878140, 0x19cccc8, 0xc00004c030, 0x19bcd48, 0xc000710c00, 0x1490fa0, 0xc000757020, 0x0, 0x0, 0x0, ...)
	github.com/nayotta/floor15/pkg/service/winery/maker_brew.go:80 +0x17c8 fp=0xc0009cccf8 sp=0xc0009cb700 pc=0x1228928
github.com/nayotta/floor15/pkg/winery/maker/machinery.(*MachineryWineryMaker).Brew(0xc00020afc0, 0xc000d3a000, 0xa4, 0x10, 0x0)
	github.com/nayotta/floor15/pkg/winery/maker/machinery/brew.go:50 +0xe9a fp=0xc0009cd890 sp=0xc0009cccf8 pc=0x132a51a
github.com/nayotta/floor15/pkg/winery/maker/machinery.(*MachineryWineryMaker).Brew-fm(0xc000d3a000, 0xa4, 0x0, 0x0)
	github.com/nayotta/floor15/pkg/winery/maker/machinery/brew.go:15 +0x47 fp=0xc0009cd8c8 sp=0xc0009cd890 pc=0x132bb07
runtime.call32(0xc0003e06f0, 0xc00073ca30, 0xc000710b80, 0x1000000020)
	runtime/asm_amd64.s:551 +0x3e fp=0xc0009cd8f8 sp=0xc0009cd8c8 pc=0x46b59e
reflect.Value.call(0x143fa00, 0xc00073ca30, 0x13, 0x16a25df, 0x4, 0xc0006d7ed8, 0x1, 0x1, 0x15bdc80, 0x161ea20, ...)
	reflect/value.go:476 +0x8e7 fp=0xc0009cdb00 sp=0xc0009cd8f8 pc=0x49d727
reflect.Value.Call(0x143fa00, 0xc00073ca30, 0x13, 0xc0006d7ed8, 0x1, 0x1, 0x19cccc8, 0xc00004c030, 0x19de6c8)
	reflect/value.go:337 +0xb9 fp=0xc0009cdb80 sp=0xc0009cdb00 pc=0x49cbf9
github.com/RichardKnop/machinery/v2/tasks.(*Task).Call(0xc000a2b540, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/RichardKnop/machinery/v2@v2.0.11/tasks/task.go:142 +0x270 fp=0xc0009cdd00 sp=0xc0009cdb80 pc=0xc6f5d0
github.com/RichardKnop/machinery/v2.(*Worker).Process(0xc0004fe870, 0xc000018000, 0x0, 0x0)
	github.com/RichardKnop/machinery/v2@v2.0.11/worker.go:182 +0x390 fp=0xc0009cde40 sp=0xc0009cdd00 pc=0x10bffd0
github.com/RichardKnop/machinery/v2/brokers/redis.(*BrokerGR).consumeOne(0xc0002a9380, 0xc000d34280, 0x26c, 0x280, 0x19c6800, 0xc0004fe870, 0x0, 0x2)
	github.com/RichardKnop/machinery/v2@v2.0.11/brokers/redis/goredis.go:317 +0x232 fp=0xc0009cdf30 sp=0xc0009cde40 pc=0x10cbd52
github.com/RichardKnop/machinery/v2/brokers/redis.(*BrokerGR).consume.func2(0xc0002a9380, 0xc000d34280, 0x26c, 0x280, 0x19c6800, 0xc0004fe870, 0xc0000a4540, 0x8, 0xc000250360)
	github.com/RichardKnop/machinery/v2@v2.0.11/brokers/redis/goredis.go:282 +0x6a fp=0xc0009cdf98 sp=0xc0009cdf30 pc=0x10ccd0a
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc0009cdfa0 sp=0xc0009cdf98 pc=0x46ce21
created by github.com/RichardKnop/machinery/v2/brokers/redis.(*BrokerGR).consume
	github.com/RichardKnop/machinery/v2@v2.0.11/brokers/redis/goredis.go:281 +0x150
```
