### ISSUE TITLE
Support `let` in es6?

### ISSUE THREAD

**Issue by wwhai** [robertkrimen/otto#406]
I want to use `let` keywords, but it  seems not support?
```js
let success = function () {
	print("success callback rule call success");
}

let failed = function (error) {
	print("failed callback ,rule call error:", error);
}
``` 
Golang:
```go
	testRun(script1)
	v, _ := jsvm.Get("success")
	t.Log("====>", v)
```

Out:
```
=== RUN   TestRunJS
    hello_test.go:81: ====> undefined
--- FAIL: TestRunJS (0.00s)
panic: !ok1 [recovered]
        panic: !ok1

goroutine 6 [running]:
testing.tRunner.func1.1(0x14656c0, 0x1581af0)
        /usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000001800)
        /usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1075 +0x41a
panic(0x14656c0, 0x1581af0)
        /usr/local/Cellar/go/1.15.3/libexec/src/runtime/panic.go:969 +0x1b9
rule_engine/test.TestRunJS(0xc000001800)
        /Users/wangwenhai/github/golang/rule_engine/test/hello_test.go:84 +0x2eb
testing.tRunner(0xc000001800, 0x150c4c0)
        /usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
        /usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1168 +0x2b3
FAIL    rule_engine/test        0.488s
FAIL
```

But when I change `let` to `var` it works!

**Comment by Asday** [comment]
Otto is an ES5 engine.

ES6 features are not supported and as far as I know, not planned.

It says this in the readme.

**Comment by wwhai** [comment]
> Otto is an ES5 engine.
> 
> ES6 features are not supported and as far as I know, not planned.
> 
> It says this in the readme.

It's my mistake，I have resolved。
