### ISSUE TITLE
fatal error: concurrent map write

### ISSUE THREAD

**Issue by s00500** [robertkrimen/otto#509]
I got a pretty strange crash today...

Notice that this is the first time I have seen this:

 	github.com/robertkrimen/otto@v0.2.1/object.go:136
 github.com/robertkrimen/otto.(*_object)._write(...)
 goroutine 797 [running]:
 github.com/robertkrimen/otto.objectDefineOwnProperty(0x40025cc120, {0x4000506dd5, 0x5}, {{0x14a2420?, 0x4004239158?}, 0x1cb3c?}, 0x0)
 	github.com/robertkrimen/otto@v0.2.1/object_class.go:436 +0x748
 github.com/robertkrimen/otto.(*_object).defineOwnProperty(...)
 	github.com/robertkrimen/otto@v0.2.1/object.go:110
 	github.com/robertkrimen/otto@v0.2.1/object.go:52
 	github.com/robertkrimen/otto@v0.2.1/object_class.go:263 +0xc8
 github.com/robertkrimen/otto.(*_object).put(...)
 github.com/robertkrimen/otto.(*_propertyReference).putValue(0x40041699a8?, {0x1a9c0?, {0x131bda0?, 0x731cec0?}})
 github.com/robertkrimen/otto.objectPut(0x40025cc120, {0x4000506dd5, 0x5}, {0x2, {0x131bda0, 0x731cec0}}, 0x0)
 	github.com/robertkrimen/otto@v0.2.1/type_reference.go:45 +0x5c
 github.com/robertkrimen/otto.(*_runtime).putValue(0x400649db00, {0x6b67540?, 0x4004914210?}, {0x4000506dd5?, {0x131bda0?, 0x731cec0?}})
 	github.com/robertkrimen/otto@v0.2.1/runtime.go:111 +0x54
 	github.com/robertkrimen/otto@v0.2.1/cmpl_evaluate_expression.go:450 +0xc0
 	github.com/robertkrimen/otto@v0.2.1/cmpl_evaluate_statement.go:102 +0x8ec
 github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0x400649db00, {0x6b5eca0?, 0x4004238c60})
 github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeVariableExpression(0x400649db00, 0x4004247d10)
 	github.com/robertkrimen/otto@v0.2.1/cmpl_evaluate.go:17 +0x160
 	github.com/robertkrimen/otto@v0.2.1/cmpl_evaluate_statement.go:119 +0x90
 	github.com/robertkrimen/otto@v0.2.1/runtime.go:839 +0x30
 github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0x400649db00, 0x400421a4d0, 0x0)
 github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0x400649db00?, {0x400421a460?, 0x7, 0x297?})
 github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
 github.com/robertkrimen/otto.catchPanic(0x4005958e68?)
 	github.com/robertkrimen/otto@v0.2.1/error.go:255 +0x58
 	github.com/robertkrimen/otto@v0.2.1/runtime.go:838 +0x8c
 	github.com/robertkrimen/otto@v0.2.1/runtime.go:851
 github.com/robertkrimen/otto.(*_runtime).cmpl_run(...)
 github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0x400649db00, {0x131c660?, 0x40046c2530?}, {0x0?, 0x0?}, 0x0)
 	github.com/robertkrimen/otto@v0.2.1/otto.go:293 +0x44
 	reactor/dispatch/DScripts.go:218 +0x1a0
 	reactor/dispatch/DScripts.go:276 +0x17c
 created by reactor/dispatch.(*Script).ManageState
 github.com/robertkrimen/otto.Otto.Run({0x4001257020?, 0x400649db00?}, {0x131c660?, 0x40046c2530?})
 reactor/dispatch.(*Script).runScript(0x4000a83680)
 
 
 
 Any idea what could have caused this exactly ?
 
 Could this change be related: https://github.com/robertkrimen/otto/commit/fc4074c6167d94ae06b7f48f62256973254c6b66 ?
 
 Greetings,
 Lukas

**Comment by stevenh** [comment]
`concurrent map write` indicates two or more goroutines we're trying to access the map at the same time.

The crash should have had multiple stacks should indicate why.

**Comment by stevenh** [comment]
Sounds like your dispatch could be reusing a VM for multiple requests? If this is case you need to lock it to prevent concurrent access.

**Comment by s00500** [comment]
Uff, just found that the mutex supposed to protect the structure holding the vm is never used.... not my code... but should have checked closer first.... sorry for opening this issue...

**Comment by stevenh** [comment]
Glad the pointers helped
