### ISSUE TITLE
The code below results in error.

### ISSUE THREAD

**Issue by yueqili** [robertkrimen/otto#75]
```
package main
import (
	"github.com/robertkrimen/otto"
	_ "github.com/robertkrimen/otto/underscore"
	"sync"
	"sort"
)

type Obj struct {
	Id int
}
var vm *otto.Otto
type TranslationBlockSlice  []*TranslationBlock
type TranslationBlock struct {
	Priority uint64
}

type PidCallGraph struct {
	sync.RWMutex
	blockArrForSort TranslationBlockSlice
}
func (this  TranslationBlockSlice)Less(i,j int)bool{
	return this[i].Priority>this[j].Priority;
}
func (this  TranslationBlockSlice)Len()int{
	return len(this)
}
func (this  TranslationBlockSlice)Swap(i,j int){
	tmp:=this[i]
	this[i]=this[j]
	this[j]=tmp
}


func (this *PidCallGraph)GetTopTranslationBlocks(num int)[]*TranslationBlock{
	this.Lock()
	defer this.Unlock()
	sort.Sort(this.blockArrForSort)
	if num<len(this.blockArrForSort) {
		for ; num > 0 && this.blockArrForSort[num] == nil; num--{

		}
	}
	return this.blockArrForSort[0:num]
}

func NewPidCallGraph() *PidCallGraph{
	r:=new(PidCallGraph)
	r.blockArrForSort=make([]*TranslationBlock,0,20000)
	return r
}
func main() {
	vm:=otto.New()
	p:=NewPidCallGraph()
	p.GetTopTranslationBlocks(100)
	vm.Set("a",p)
	_,err:=vm.Run(`var m=a.GetTopTranslationBlocks(23)
	console.log(m)
			`)
	if nil!=err{
		panic(err)
	}
}
```
```
panic: reflect: Call using int64 as type int [recovered]
panic: reflect: Call using int64 as type int

goroutine 16 [running]:
runtime.panic(0x5e2b40, 0xc2081a3c30)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/robertkrimen/otto.func·023()
	/home/leo/src/otto/src/github.com/robertkrimen/otto/error.go:147 +0x4df
runtime.panic(0x5e2b40, 0xc2081a3c30)
	/usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
reflect.Value.call(0x603e00, 0xc20810d980, 0x0, 0x130, 0x674640, 0x4, 0xc208190dc0, 0x1, 0x1, 0x0, ...)
	/usr/local/go/src/pkg/reflect/value.go:485 +0x6a1
reflect.Value.Call(0x603e00, 0xc20810d980, 0x0, 0x130, 0xc208190dc0, 0x1, 0x1, 0x130, 0x422851, 0x20)
	/usr/local/go/src/pkg/reflect/value.go:411 +0xb3
github.com/robertkrimen/otto.func·038(0xc208080000, 0x0, 0x0, 0x6, 0x6657e0, 0xc2080d5560, 0xc208190da0, 0x1, 0x1, 0xc208001240, ...)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/runtime.go:289 +0x1ce
github.com/robertkrimen/otto._nativeCallFunction.Dispatch(0x6730e0, 0x0, 0xc2081a3bf0, 0xc2080d56e0, 0xc2081e8180, 0xc208080000, 0x6, 0x6657e0, 0xc2080d5560, 0xc208190da0, ...)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/type_function.go:163 +0xed
github.com/robertkrimen/otto.(*_nativeCallFunction).Dispatch(0xc208190ca0, 0xc2080d56e0, 0xc2081e8180, 0xc208080000, 0x6, 0x6657e0, 0xc2080d5560, 0xc208190da0, 0x1, 0x1, ...)
	<autogenerated>:126 +0x12d
github.com/robertkrimen/otto.(*_runtime).Call(0xc208080000, 0xc2080d56e0, 0x6, 0x6657e0, 0xc2080d5560, 0xc208190da0, 0x1, 0x1, 0xc2081e2500, 0x0, ...)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/runtime.go:137 +0x1e6
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc208080000, 0xc20810d8c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:194 +0x591
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc208080000, 0x7f732221ff88, 0xc20810d8c0, 0x0, 0x0, 0x0)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:30 +0x7fb
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeVariableExpression(0xc208080000, 0xc208190a80, 0x0, 0x0, 0x0)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:371 +0xda
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc208080000, 0x7f732221fd58, 0xc208190a20, 0x0, 0x0, 0x0)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:76 +0x640
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc208080000, 0xc208190a00, 0x2, 0x2, 0x0, 0x0, 0x0)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:94 +0xaa
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc208080000, 0xc2080d55c0, 0x0, 0x0, 0x0)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/cmpl_evaluate.go:10 +0xaa
github.com/robertkrimen/otto.func·039()
	/home/leo/src/otto/src/github.com/robertkrimen/otto/runtime.go:356 +0x3e
github.com/robertkrimen/otto.catchPanic(0xc208099e30, 0x0, 0x0)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/error.go:150 +0x7e
github.com/robertkrimen/otto.(*_runtime).cmpl_run(0xc208080000, 0x5e2b40, 0xc2081a3a70, 0x0, 0x0, 0x0, 0x10, 0x42003d)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/runtime.go:357 +0x169
github.com/robertkrimen/otto.Otto.Run(0x0, 0xc208080000, 0x5e2b40, 0xc2081a3a70, 0x0, 0x0, 0x0, 0x0, 0x2)
	/home/leo/src/otto/src/github.com/robertkrimen/otto/otto.go:287 +0x50
main.main()
	/home/leo/src/otto/src/otto.go:60 +0x155

goroutine 19 [finalizer wait]:
runtime.park(0x412f80, 0x8d0340, 0x8cee29)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x8d0340, 0x8cee29)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2640 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445
exit status 2
```

**Comment by stevenh** [comment]
Got a fix for this one, will submit a pull request soon

**Comment by stevenh** [comment]
Fixed by: https://github.com/robertkrimen/otto/pull/104
